version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.0
    working_directory: ~/frontend
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v-{{ .Branch }}-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v-{{ .Branch }}-dependencies-

      - run: cd frontend

      - run:
          name: Install Now CLI
          command: yarn global add now --unsafe-perm

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: v-{{ .Branch }}-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - deploy:
          name: Deploy site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                now --token $NOW_TOKEN
                now --token $NOW_TOKEN alias dev.ashleyhitchcock.com
            elif [ "${CIRCLE_BRANCH}" == "release" ]; then
                now --token $NOW_TOKEN
                now --token $NOW_TOKEN alias www.ashleyhitchcock.com
            fi
