defaults: &defaults
    docker:
        - image: circleci/node:8.11.0
    working_directory: ~/repo

version: 2
jobs:
  build:
     <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v-{{ .Branch }}-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v-{{ .Branch }}-dependencies-

      - run: cd frontend

      - run:
          name: Install Now CLI
          command: yarn global add now --unsafe-perm

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v-{{ .Branch }}-dependencies-{{ checksum "package.json" }}
      - deploy:
          name: Deploy site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                now --token $NOW_TOKEN
                now --token $NOW_TOKEN alias dev.ashleyhitchcock.com
            elif [ "${CIRCLE_BRANCH}" == "release" ]; then
                now --token $NOW_TOKEN
                now --token $NOW_TOKEN alias www.ashleyhitchcock.com
            fi
      # run tests!
      #- run: yarn test
