version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    branches:
      only:
        - master
        - release

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v-{{ .Branch }}-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v-{{ .Branch }}-dependencies-

      - run: cd frontend

      - run: yarn global add now

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v-{{ .Branch }}-dependencies-{{ checksum "package.json" }}
      - deploy:
          name: Deploy site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                now --token $NOW_TOKEN
                now --token $NOW_TOKEN alias dev.ashleyhitchcock.com
            elif [ "${CIRCLE_BRANCH}" == "release" ]; then
                now --token $NOW_TOKEN
                now --token $NOW_TOKEN alias www.ashleyhitchcock.com
            fi
      # run tests!
      #- run: yarn test
